### ISSUE TITLE
axInput: builtin validators lack axInputMinimumLength validator

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar_uikit#90]
For strings there is an axInputMaximumLength validator directive but no corresponding axInputMinimumLength validator directive. The latter is e.g. necessary when validating some name containing 3 characters minimum, for example.

**Comment by x1B** [comment]
### Usage Instructions

A new validation directive for `axInput` has been added: `axInputMinimumLength` allows to validate string values against a minimum required length.

### Availability
Merged into `master` (`v1.0.0`) and `master-0.x` (`v0.20.0`).
