### ISSUE TITLE
axInput: builtin axInputMaximumLength validator throws when value is null or undefined

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar_uikit#91]
Validator implementation should be something like this:
```
return !value || value.length <= maximumLength();
```

**Comment by x1B** [comment]
The minimumLength() directive needs to be fixed at the same time.

**Comment by x1B** [comment]
Fixed on `master` (`v1.0.0`) and `master-0.x` (`v0.20.0`).
