### ISSUE TITLE
axInput: fix spec tests for AngularJS 1.3

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar_uikit#98]
Due to some breaking changes in AngularJS 1.3, the LaxarJS UiKit tests do not run with this version of AngularJS.

Additionally to this issue there is #97 which is due to problems with ngModelOptions and axInput when using AngularJS 1.3.x.

**Comment by x1B** [comment]
_Marking as question:_ From AngularJS `1.2.x` to `1.3.x`, incompatible changes have been made to the  `ngModelController`, specifically [this one](https://github.com/angular/angular.js/blob/v1.3.15/CHANGELOG.md#breaking-changes-14). Because `axInput` is already relatively complicated, maintaining compatbility with both 1.2.x and 1.3.x is probably infeasible.

**Comment by x1B** [comment]
_Unmarking question:_ From LaxarJS 0.x to 1.x, we'll move from supporting AngularJS 1.2.x to 1.3.x.

**Comment by alex3683** [comment]
Implemented on `master` (`v1.0.0-alpha.1`).
